var quotes = [

	["Make", "Pork Chops", "great again!"],
	["Make", "A Brew", "great again!"],
	["Make", "Chopsticks", "great again!"],
	["Make", "Leather", "great again!"],
	["Make", "The Internet", "great again!"],
	["Make", "The World", "great again!"],
	["Make", "The Department", "great again!"],
	["Make", "Yourself", "great again!"],
	["Make", "Your mum", "great again!"],
	["Make", "Your dad", "great again!"],
	["Make", "Your sister", "great again!"],
	["Make", "Your brother", "great again!"],
	["Make", "Karen", "great again!"],
	["Make", "Anything", "great again!"],
	["Make", "Everything", "great again!"],
	["Make", "Fried Chicken", "great again!"],
	["Make", "Television", "great again!"],
	["Make", "Memes", "great again!"],
	["Make", "Jokes", "great again!"],
	["Make", "Spray tan", "great again!"],
	["Make", "Swearing", "great again!"],
	["Make", "Tucking", "great again!"],
	["Make", "Nothing", "great again!"],
	["Make", "The nineties", "great again!"],
	["Make", "The Spice Girls", "great again!"],
	["Make", "Girls Aloud", "great again!"],
	["Make", "The Thick Of It", "great again!"],
	["Make", "Politics", "great again!"],
	["Make", "Dancing", "great again!"],
	["Make", "Money", "great again!"],
	["Make", "The Economy", "great again!"],
	["Make", "Your Love Live", "great again!"],
	["Make", "Government", "great again!"],
	["Make", "Governance", "great again!"],
	["Make", "Admnistration", "great again!"],
	["Make", "Services", "great again!"],
	["Make", "Your dreams", "great again!"],
	["Make", "Your nightmares", "great again!"],
	["Make", "Your hopes", "great again!"],
	["Make", "Your desires", "great again!"],
	["Make", "Your fears", "great again!"],
	["Make", "Bad Ideas", "great again!"],
	["Make", "Good Ideas", "great again!"],
	["Make", "Your nan", "great again!"],
	["Make", "Twitter", "great again!"],
	["Make", "Facebook", "great again!"],
	["Make", "Twitter bots", "great again!"],
	["Make", "Instagram", "great again!"],
	["Make", "Feather Boas", "great again!"],
	["Make", "Show Tunes", "great again!"],
	["Make", "Pop music", "great again!"],
	["Make", "Eurovision", "great again!"],
	["Make", "Your country", "great again!"],
	["Make", "Your life", "great again!"],
	["Make", "Cooking", "great again!"],
	["Make", "Eating", "great again!"],
	["Make", "Tweeting", "great again!"],
	["Make", "Selfies", "great again!"],
	["Make", "Kittens", "great again!"],
	["Make", "Pastry", "great again!"],
	["Make", "Sport", "great again!"],
	["Make", "Cinema", "great again!"],
	["Make", "The railways", "great again!"],
	["Make", "Kebabs", "great again!"],
	["Make", "Children", "great again!"],
	["Make", "Old people", "great again!"],
	["Make", "Adulting", "great again!"],
	["Make", "Sexy time", "great again!"],
	["Make", "Great", "great again!"],
	["Make", "Tony The Tiger", "great again!"],
	["Make", "Antman", "great again!"],
	["Make", "Spiderman", "great again!"],
	["Make", "Superman", "great again!"],
	["Make", "Batman", "great again!"],
	["Make", "Supergirl", "great again!"],
	["Make", "Catwoman", "great again!"],
	["Make", "The Joker", "great again!"],
	["Make", "Your Pay Cheque", "great again!"],
	["Make", "Netflix", "great again!"],
	["Make", "Amazon", "great again!"],
	["Make", "Apple", "great again!"],
	["Make", "Google", "great again!"],
	["Make", "Microsoft", "great again!"],
	["Make", "Spreadsheets", "great again!"],
	["Make", "Outlook", "great again!"],
	["Make", "Email", "great again!"],
	["Make", "Text messaging", "great again!"],
	["Make", "Whatsapp", "great again!"],
	["Make", "Glamour", "great again!"],
	["Make", "Glamazons", "great again!"],
	["Make", "Happiness", "great again!"],
	["Make", "Lockdown", "great again!"],
	["Make", "Quarantine", "great again!"],
	["Make", "Housework", "great again!"],
	["Make", "Exercise", "great again!"],
	["Make", "Intelligence", "great again!"],
	["Make", "Intellect", "great again!"],
	["Make", "The weather", "great again!"],
	["Make", "Your home", "great again!"],
	["Make", "Your waistline", "great again!"],
	["Make", "Thursting", "great again!"],
	["Make", "Socialising", "great again!"],
	["Make", "The pub", "great again!"],
	["Make", "Your wallet", "great again!"],
	["Make", "Your purse", "great again!"],
	["Make", "Conversation", "great again!"],
	["Make", "Schnitzel", "great again!"],

];
  
module.exports = quotes;