var quotes = [

	["Make", "Pork Chops", "great again!"],
	["Make", "A Brew", "great again!"],
	["Make", "Chopsticks", "great again!"],
	["Make", "Leather", "great again!"],
	["Make", "The Internet", "great again!"],
	["Make", "The World", "great again!"],
	["Make", "The Department", "great again!"],
	["Make", "Yourself", "great again!"],
	["Make", "Your mum", "great again!"],
	["Make", "Your dad", "great again!"],
	["Make", "Your sister", "great again!"],
	["Make", "Your brother", "great again!"],
	["Make", "Karen", "great again!"],
	["Make", "Anything", "great again!"],
	["Make", "Everything", "great again!"],
	["Make", "Fried Chicken", "great again!"],
	["Make", "Television", "great again!"],
	["Make", "Memes", "great again!"],
	["Make", "Jokes", "great again!"],
	["Make", "Spray tan", "great again!"],
	["Make", "Swearing", "great again!"],
	["Make", "Tucking", "great again!"],
	["Make", "Nothing", "great again!"],
	["Make", "The nineties", "great again!"],
	["Make", "The Spice Girls", "great again!"],
	["Make", "Girls Aloud", "great again!"],
	["Make", "The Thick Of It", "great again!"],
	["Make", "Politics", "great again!"],
	["Make", "Dancing", "great again!"],
	["Make", "Money", "great again!"],
	["Make", "The Economy", "great again!"],
	["Make", "Your Love Live", "great again!"],
	["Make", "Government", "great again!"],
	["Make", "Governance", "great again!"],
	["Make", "Admnistration", "great again!"],
	["Make", "Services", "great again!"],
	["Make", "Your dreams", "great again!"],
	["Make", "Your nightmares", "great again!"],
	["Make", "Your hopes", "great again!"],
	["Make", "Your desires", "great again!"],
	["Make", "Your fears", "great again!"],

];
  
module.exports = quotes;